server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/api/music/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
