spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/api/music/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
