server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # ← ЭТОЙ СТРОЧКИ НЕ ХВАТАЕТ!
      routes:
        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/api/music/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway  # ← добавил gateway для диагностики
