server:
  port: 8082

spring:
  application:
    name: player-service
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.musicplatform.playerservice: DEBUG
    org.springframework.web.reactive: DEBUG

spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID:3b72d6c465bf4859b93d959032307d3e}
    secret: ${SPOTIFY_CLIENT_SECRET:71b6f1d77dbe4aa8bd10065627e6cc67}
  api:
    url: https://api.spotify.com/v1
  auth:
    url: https://accounts.spotify.com/api/token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
